server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.177.177

gmall:
  jwt:
    pubKeyPath: E:\\temp\\rsa\\rsa.pub #公钥存储路径
    cookieName: GMALL_TOKEN
    userKey: userKey
    expire : 22500
